#!/usr/env/bin bash

function git_prompt() {
    (git symbolic-ref -q HEAD || git name-rev --name-only --no-undefined --always HEAD ) 2> /dev/null | cut -d'/' -f3
}

# prompt
PROMPT=$'%F{green}>>> %B%F{cyan}%~ %1(j,%F{red}:%j,)%F{blue}$(git_prompt) \n%F{white}%B%(?..[%?] )%{%F{red}%}%# %F{white}%b'
